project_id = "hqpwepmdxzmuevalzkix"

[functions.tesla-start]
verify_jwt = true

[functions.tesla-auth]
verify_jwt = true

[functions.tesla-vehicles]
verify_jwt = true

[functions.tesla-mileage]
verify_jwt = true

[functions.tesla-register]
verify_jwt = true

[functions.tesla-disconnect]
verify_jwt = true

[functions.tesla-sync-all]
verify_jwt = false
